# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'routing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrouting.proto\x12\x07routing\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xd8\x01\n\x0cRouteRequest\x12\x11\n\tstart_lon\x18\x01 \x01(\x01\x12\x11\n\tstart_lat\x18\x02 \x01(\x01\x12\x0f\n\x07\x65nd_lon\x18\x03 \x01(\x01\x12\x0f\n\x07\x65nd_lat\x18\x04 \x01(\x01\x12\x15\n\rmax_transfers\x18\x05 \x01(\x05\x12\x16\n\x0ewalking_cutoff\x18\x06 \x01(\x01\x12\x18\n\x10restricted_modes\x18\x07 \x03(\t\x12(\n\x07weights\x18\x08 \x01(\x0b\x32\x17.routing.RoutingWeights\x12\r\n\x05top_k\x18\t \x01(\x05\"L\n\x0eRoutingWeights\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x01\x12\x0c\n\x04walk\x18\x03 \x01(\x01\x12\x10\n\x08transfer\x18\x04 \x01(\x01\"&\n\rRouteResponse\x12\x15\n\rjourneys_json\x18\x01 \x01(\t2\x90\x01\n\x0eRoutingService\x12@\n\x0bHealthCheck\x12\x16.routing.HealthRequest\x1a\x17.routing.HealthResponse\"\x00\x12<\n\tFindRoute\x12\x15.routing.RouteRequest\x1a\x16.routing.RouteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=26
  _globals['_HEALTHREQUEST']._serialized_end=41
  _globals['_HEALTHRESPONSE']._serialized_start=43
  _globals['_HEALTHRESPONSE']._serialized_end=92
  _globals['_ROUTEREQUEST']._serialized_start=95
  _globals['_ROUTEREQUEST']._serialized_end=311
  _globals['_ROUTINGWEIGHTS']._serialized_start=313
  _globals['_ROUTINGWEIGHTS']._serialized_end=389
  _globals['_ROUTERESPONSE']._serialized_start=391
  _globals['_ROUTERESPONSE']._serialized_end=429
  _globals['_ROUTINGSERVICE']._serialized_start=432
  _globals['_ROUTINGSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
